# Generated by Django 4.0.4 on 2022-05-28 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_calenders', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(max_length=15)),
                ('main_id', models.EmailField(max_length=254, unique=True)),
                ('profile', models.URLField(default='')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_calenders.department')),
            ],
        ),
    ]
