# Generated by Django 4.0.4 on 2022-05-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffdetails',
            name='profile',
            field=models.URLField(blank=True, default=''),
        ),
    ]
