# Generated by Django 4.0.4 on 2022-05-28 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calenders', '0002_graduation'),
        ('syllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='graduation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_calenders.graduation'),
        ),
    ]
