# Generated by Django 4.0.4 on 2022-05-29 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calenders', '0010_academiccalender_batch'),
        ('syllabus', '0002_alter_syllabus_graduation'),
    ]

    operations = [
        migrations.AddField(
            model_name='syllabus',
            name='batch',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='academic_calenders.batch'),
            preserve_default=False,
        ),
    ]
