# Generated by Django 4.0.4 on 2022-05-28 16:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulation', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicCalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000, unique=True)),
                ('doc_url', models.URLField(max_length=1000)),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
                ('regulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_calenders.regulation')),
            ],
        ),
    ]
