# Generated by Django 4.0.4 on 2022-05-29 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calenders', '0003_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
