# Generated by Django 4.0.4 on 2022-05-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calenders', '0005_batch_department_department_graduation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='batch',
            field=models.CharField(max_length=10),
        ),
    ]
