# Generated by Django 4.0.4 on 2022-05-29 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calenders', '0007_batch_graduation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='batch',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='academic_calenders.batch'),
            preserve_default=False,
        ),
    ]
