# Generated by Django 4.0.4 on 2022-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_calenders', '0008_remove_batch_department_department_batch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=50),
        ),
    ]
